CREATE DATABASE PROFIL;
USE PROFIL;

CREATE TABLE TMahasiswa (
	NIM VARCHAR(8) PRIMARY KEY,
	NAMA VARCHAR(30) NOT NULL,
	DOB DATE NOT NULL,
	EMAIL VARCHAR(50)
)
	
CREATE TABLE TMataKuliah(
	ID VARCHAR(5) PRIMARY KEY,
	NAMA_MATKUL VARCHAR(30) NOT NULL
)

CREATE TABLE TmhsMatkul(
	ID VARCHAR(5),
	NIM VARCHAR(5),
	FOREIGN KEY(ID) REFERENCES TMataKuliah(ID),
	FOREIGN KEY(NIM) REFERENCES TMahasiswa(NIM),
	PRIMARY KEY(ID, NIM)
)